# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('fees', models.FloatField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('service_one', models.CharField(blank=True, max_length=200, null=True)),
                ('service_one_is_available', models.NullBooleanField(default=True)),
                ('service_two', models.CharField(blank=True, max_length=200, null=True)),
                ('service_two_is_available', models.NullBooleanField(default=True)),
                ('service_three', models.CharField(blank=True, max_length=200, null=True)),
                ('service_three_is_available', models.NullBooleanField(default=True)),
                ('service_four', models.CharField(blank=True, max_length=200, null=True)),
                ('service_four_is_available', models.NullBooleanField(default=True)),
                ('service_five', models.CharField(blank=True, max_length=200, null=True)),
                ('service_five_is_available', models.NullBooleanField(default=True)),
                ('service_six', models.CharField(blank=True, max_length=200, null=True)),
                ('service_six_is_available', models.NullBooleanField(default=True)),
                ('service_seven', models.CharField(blank=True, max_length=200, null=True)),
                ('service_seven_is_available', models.NullBooleanField(default=True)),
                ('service_eight', models.CharField(blank=True, max_length=200, null=True)),
                ('service_eight_is_available', models.NullBooleanField(default=True)),
                ('service_nine', models.CharField(blank=True, max_length=200, null=True)),
                ('service_nine_is_available', models.NullBooleanField(default=True)),
                ('service_ten', models.CharField(blank=True, max_length=200, null=True)),
                ('service_ten_is_available', models.NullBooleanField(default=True)),
                ('service_eleven', models.CharField(blank=True, max_length=200, null=True)),
                ('service_eleven_is_available', models.NullBooleanField(default=True)),
                ('service_twelve', models.CharField(blank=True, max_length=200, null=True)),
                ('service_twelve_is_available', models.NullBooleanField(default=True)),
                ('service_thirteen', models.CharField(blank=True, max_length=200, null=True)),
                ('service_thirteen_is_available', models.NullBooleanField(default=True)),
                ('service_fourteen', models.CharField(blank=True, max_length=200, null=True)),
                ('service_fourteen_is_available', models.NullBooleanField(default=True)),
                ('service_fifteen', models.CharField(blank=True, max_length=200, null=True)),
                ('service_fifteen_is_available', models.NullBooleanField(default=True)),
                ('service_sixteen', models.CharField(blank=True, max_length=200, null=True)),
                ('service_sixteen_is_available', models.NullBooleanField(default=True)),
                ('service_seventeen', models.CharField(blank=True, max_length=200, null=True)),
                ('service_seventeen_is_available', models.NullBooleanField(default=True)),
                ('service_eighteen', models.CharField(blank=True, max_length=200, null=True)),
                ('service_eighteen_is_available', models.NullBooleanField(default=True)),
                ('service_nineteen', models.CharField(blank=True, max_length=200, null=True)),
                ('service_nineteen_is_available', models.NullBooleanField(default=True)),
                ('service_twenty', models.CharField(blank=True, max_length=200, null=True)),
                ('service_twenty_is_available', models.NullBooleanField(default=True)),
                ('service_twentyone', models.CharField(blank=True, max_length=200, null=True)),
                ('service_twentyone_is_available', models.NullBooleanField(default=True)),
                ('service_twentytwo', models.CharField(blank=True, max_length=200, null=True)),
                ('service_twentytwo_is_available', models.NullBooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
            },
        ),
    ]
