# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-01 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='customer',
            new_name='user',
        ),
    ]
