# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-01 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181130_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='link',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='link_title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
