# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='invoice',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
