# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=400, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
