# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_statement', models.CharField(blank=True, max_length=150)),
                ('address1', models.CharField(blank=True, max_length=150)),
                ('address2', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=150)),
                ('zipcode', models.CharField(blank=True, max_length=150)),
                ('tollfree', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('fax', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('header', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Contanct Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos')),
                ('widht', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='LogoColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Logo Color',
                'verbose_name_plural': 'Logo Colors',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('text', models.CharField(blank=True, max_length=450)),
                ('link', models.CharField(blank=True, max_length=350)),
                ('slide', models.ImageField(upload_to='slides')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slide',
            },
        ),
        migrations.AddField(
            model_name='logo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_color', to='gui.LogoColor'),
        ),
    ]
