# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('text', models.CharField(blank=True, max_length=450)),
                ('link', models.CharField(blank=True, max_length=350)),
                ('slide', models.ImageField(upload_to='avatars')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slide',
            },
        ),
    ]
