# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20160826_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
