# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 02:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_auto_20160826_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000),
        ),
    ]
