# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 03:24
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20160826_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
