# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 04:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_auto_20160826_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2500),
        ),
    ]
