# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 04:30
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_auto_20160827_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
