# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 04:53
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0010_auto_20160827_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=redactor.fields.RedactorField(verbose_name='Description'),
        ),
    ]
